name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Determine Docker image tag
      id: version
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag almbolonzi/web-app:${{ steps.version.outputs.tag }}
    - name: Docker tag as latest
      run: docker tag almbolonzi/web-app:${{ steps.version.outputs.tag }} almbolonzi/web-app:latest
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker image
      run: |
        docker push almbolonzi/web-app:${{ steps.version.outputs.tag }}
        docker push almbolonzi/web-app:latest
