name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract metadata (optional)
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Configure tag patterns as needed
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU (optional, adjust as needed)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (optional, adjust as needed)
        uses: docker/setup-buildx-action@v3

      - name: Docker login (optional)
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag almbolonzi/web-app:${{ steps.meta.outputs.tags }}

      - name: Push docker image (optional)
        if: github.event_name != 'pull_request'
        run: docker push almbolonzi/web-app:${{ steps.meta.outputs.tags }}

